name: Feature Request
description: Request a new feature
title: "[Feature] "
labels: ["type: feature", "scope: user"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you submit the request
        - Make sure...
          - you use the latest released version of the add-on
          - the same feature was not requested before
        - Consider if others would benefit from the feature as well (niche personal features without broader application probably won't be worked on)
  - type: dropdown
    id: type
    attributes:
      label: Category
      description:
      options:
        - Import-Export
        - Tool
        - Utility
        - Utility Script
        - Other (please specify in the description)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature you'd like to see in detail! (You can include images, and other attachments.)
      placeholder: The feature I'd like to request is...
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: Optional contact info (discord, email, etc.) for if we need further information
      placeholder: ex. email@example.com
    validations:
      required: false
